### ISSUE TITLE
About evaluation

### ISSUE THREAD

**Issue by PURE-melo** [meiqihu/HyperNet#1]
Hi~Thanks for your nice work. Could you please provide the code to evaluate HBCD?

**Comment by meiqihu** [comment]
Thank you for your message and support of our work. The code will uploaded within tomorrow.

2023-03-21 17:19:25PUREMELO ***@***.***>写道：

Hi~Thanks for your nice work. Could you please provide the code to evaluate HBCD?

**Comment by PURE-melo** [comment]
Many thanks for your reply! Looking forward to your code.
